-- MySQL Script generated by MySQL Workbench
-- Sun Jan 16 01:12:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sd_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sd_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sd_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sd_db` ;

-- -----------------------------------------------------
-- Table `sd_db`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd_db`.`administrador` (
  `idAdministrador` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  UNIQUE INDEX `idAdministrador` (`idAdministrador` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sd_db`.`utilizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd_db`.`utilizador` (
  `idUtilizador` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(30) NOT NULL,
  `Tipo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idUtilizador`),
  UNIQUE INDEX `idUtilizador` (`idUtilizador` ASC) VISIBLE,
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sd_db`.`voo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd_db`.`voo` (
  `idVoo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Partida` VARCHAR(100) NOT NULL,
  `Destino` VARCHAR(100) NOT NULL,
  `Capacidade` INT NOT NULL,
  `Duracao` INT NOT NULL,
  PRIMARY KEY (`idVoo`),
  UNIQUE INDEX `idVoo` (`idVoo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sd_db`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd_db`.`reserva` (
  `idReserva` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUtilizador` INT UNSIGNED NOT NULL,
  `idVoo` INT UNSIGNED NOT NULL,
  `Data_Reserva` DATETIME NOT NULL,
  `Data_Voo` DATETIME NOT NULL,
  PRIMARY KEY (`idReserva`),
  UNIQUE INDEX `idReserva` (`idReserva` ASC) VISIBLE,
  INDEX `fk_Registo_Utilizador_idx` (`idUtilizador` ASC) VISIBLE,
  INDEX `fk_Reserva_Voo1_idx` (`idVoo` ASC) VISIBLE,
  CONSTRAINT `fk_Registo_Utilizador`
    FOREIGN KEY (`idUtilizador`)
    REFERENCES `sd_db`.`utilizador` (`idUtilizador`),
  CONSTRAINT `fk_Reserva_Voo1`
    FOREIGN KEY (`idVoo`)
    REFERENCES `sd_db`.`voo` (`idVoo`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sd_db`.`utilizadornormal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sd_db`.`utilizadornormal` (
  `idUtilizadorNormal` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUtilizadorNormal`),
  UNIQUE INDEX `idUtilizadorNormal` (`idUtilizadorNormal` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
